Controllers/Components/LoginStatusViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TeamUp.Core.Models;

namespace TeamUp.Controllers.Components
{
    public class LoginStatusViewComponent : ViewComponent
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public LoginStatusViewComponent(
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                return View("Loggedin", user);
            }
            return View("Anonymous");
        }
    }
}

Controllers/Components/SideBarViewComponent.cs
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TeamUp.Core;
using TeamUp.Core.Models;
using TeamUp.Core.ViewModels;

namespace TeamUp.Controllers.Components
{
    public class SideBarViewComponent : ViewComponent
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public SideBarViewComponent(
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager,
            IUnitOfWork unitOfWork,
            IMapper mapper)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (!_signInManager.IsSignedIn(HttpContext.User)) return View();

            var userId = _userManager.GetUserId(HttpContext.User);
            var user = await _unitOfWork.Users.GetUserById(userId);
            var viewModel = _mapper.Map<ApplicationUser, MemberInfoViewModel>(user);
            return View("SideBar", viewModel);
        }
    }
}

Controllers/MembersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TeamUp.Core;
using TeamUp.Core.Enums;
using TeamUp.Core.Models;
using TeamUp.Core.ViewModels;

namespace TeamUp.Controllers
{
    public class MembersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;

        public MembersController(
            IUnitOfWork unitOfWork,
            UserManager<ApplicationUser> userManager,
            IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Info(string id)
        {
            var user = await _unitOfWork.Users.GetUserById(id);
            if (user == null)
                return NotFound("User not found");

            var viewModel = _mapper.Map<ApplicationUser, MemberInfoViewModel>(user);

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var users = await _unitOfWork.Users.GetUsers();
            var viewModel = _mapper.Map<IEnumerable<ApplicationUser>, IEnumerable<MemberInfoViewModel>>(users);

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit()
        {
            var user = await GetCurrentUser();
            var viewModel = _mapper.Map<ApplicationUser, MemberEditViewModel>(user);
            viewModel.PopulateList(
                _unitOfWork.Locations.GetCities(), 
                _unitOfWork.Locations.GetDistricts(user.District.CityId),
                _unitOfWork.Positions.GetPositions());
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MemberEditViewModel viewModel)
        {
            var user = await GetCurrentUser();
            _mapper.Map(viewModel, user);
            await _unitOfWork.CompleteAsync();
            return RedirectToAction("Info", new { id = user.Id });
        }

        public async Task<IActionResult> Requests()
        {
            var userRequests = await _unitOfWork.Requests.GetAllRequestsForUser(_userManager.GetUserId(HttpContext.User));
            var requests = userRequests
                .Where(r => r.Type == RequestType.FromMember);
            var invitations = userRequests
                .Where(r => r.Type == RequestType.FromTeam && r.Status == RequestStatus.Pending);

            var viewModel = new MembersRequestsViewModel
            {
                Requests = _mapper.Map<IEnumerable<Request>, IEnumerable<JoinRequestViewModel>>(requests),
                Invitations = _mapper.Map<IEnumerable<Request>, IEnumerable<JoinRequestViewModel>>(invitations)
            };

            return View(viewModel);
        }

        private async Task<ApplicationUser> GetCurrentUser()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            return await _unitOfWork.Users.GetUserById(userId);
        }
    }
}

Controllers/TeamsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TeamUp.Core;
using TeamUp.Core.Enums;
using TeamUp.Core.Models;
using TeamUp.Core.ViewModels;

namespace TeamUp.Controllers
{
    public class TeamsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public TeamsController(
            IUnitOfWork unitOfWork,
            IMapper mapper,
            UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var teams = await _unitOfWork.Teams.GetTeams();

            var viewModel = new TeamListViewModel
            {
                Teams = _mapper.Map<IEnumerable<Team>, IEnumerable<TeamInfoViewModel>>(teams),
            };

            return View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            var user = await GetCurrentUserAsync();

            if (user.TeamId.HasValue)
                return BadRequest("You've had a team.");

            var viewModel = new SaveTeamViewModel();
            viewModel.PopulateLocationList(_unitOfWork.Locations.GetCities());

            return View("TeamForm", viewModel);
        }

        public IActionResult ValidateTeamName(string name, string initialName)
        {
            if (name == initialName)
                return Json(true);

            return Json(_unitOfWork.Teams.CheckTeamNameExists(name) ? $"Tên {name} đã có người khác chọn." : "true");
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(SaveTeamViewModel saveTeam)
        {
            if (!ModelState.IsValid)
                return View("TeamForm");

            var user = await GetCurrentUserAsync();
            var team = new Team(user);
            _mapper.Map(saveTeam, team);

            await _unitOfWork.Teams.AddAsync(team);
            await _unitOfWork.CompleteAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Info(int id)
        {
            var team = await _unitOfWork.Teams.GetTeam(id);
            var viewModel = _mapper.Map<Team, TeamInfoViewModel>(team);
            var requests = await _unitOfWork.Requests.GetAllPendingRequestsForTeam(id);
            viewModel.JoinRequests = _mapper.Map<IEnumerable<Request>, IEnumerable<JoinRequestViewModel>>(requests);

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Requests(int id)
        {
            var teamRequests = await _unitOfWork.Requests.GetAllRequestsForTeam(id);
            var requests = teamRequests
                .Where(r => r.Type == RequestType.FromMember && r.Status == RequestStatus.Pending);
            var invitations = teamRequests
                .Where(r => r.Type == RequestType.FromTeam);

            var viewModel = new MembersRequestsViewModel
            {
                Requests = _mapper.Map<IEnumerable<Request>, IEnumerable<JoinRequestViewModel>>(requests),
                Invitations = _mapper.Map<IEnumerable<Request>, IEnumerable<JoinRequestViewModel>>(invitations)
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var team = await _unitOfWork.Teams.GetTeam(id);
            if (team == null)
                return NotFound();

            var viewModel = new TeamEditViewModel();
            viewModel.PopulateLocationList(
                _unitOfWork.Locations.GetCities(),
                _unitOfWork.Locations.GetDistricts(team.District.CityId));


            _mapper.Map(team, viewModel);

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TeamEditViewModel viewModel)
        {
            var team = await _unitOfWork.Teams.GetTeam(viewModel.Id);
            if (team == null)
                return NotFound();

            _mapper.Map(viewModel, team);

            await _unitOfWork.CompleteAsync();

            return RedirectToAction("Info", new { id = team.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var team = await _unitOfWork.Teams.GetTeam(id, loadRelated: false);

            if (team == null)
                return NotFound();

            _unitOfWork.Teams.Delete(team);
            await _unitOfWork.CompleteAsync();

            return RedirectToAction("Index");
        }

        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeamUp</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/lib/bootstrap-paper/bootstrap-paper.css" rel="stylesheet" />
        <link href="~/lib/sweetalert/dist/sweetalert.css" rel="stylesheet" />
        <link href="~/lib/jquery-ui/themes/base/theme.css" rel="stylesheet" />
        <link href="~/lib/jquery-ui/themes/base/datepicker.css" rel="stylesheet" />
        <link href="~/lib/jcrop/css/jquery.Jcrop.css" rel="stylesheet" />
        <link href="~/lib/Croppie/croppie.css" rel="stylesheet" />
        <link href="~/css/image-upload.css" rel="stylesheet" />
        <link href="~/css/member-info.css" rel="stylesheet" />
        <link href="~/css/member-edit.css" rel="stylesheet" />
        <link href="~/css/team-info.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    @Html.Partial("_NavBar")
    @if (User.Identity.IsAuthenticated)
    {
        @await Component.InvokeAsync("SideBar");
        <div class="container-fluid content">
            <div class="row">
                <div class="col-md-10 col-md-offset-2">
                    @RenderBody()
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="container body-content">
            <div class="row">
                @RenderBody()
            </div>
            <div class="row">
                <hr />
                <footer>
                    <p>&copy; 2017 - TeamUp</p>
                </footer>
            </div>
        </div>
    }
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/sweetalert/dist/sweetalert.min.js"></script>
        <script src="~/app/services/requestService.js"></script>
        <script src="~/app/services/teamService.js"></script>
        <script src="~/app/services/photoService.js"></script>
        <script src="~/app/controllers/teamsController.js"></script>
        <script src="~/app/controllers/teamInfoController.js"></script>
        <script src="~/app/controllers/memberInfoController.js"></script>
        <script src="~/app/controllers/photosController.js"></script>>
        <script src="~/app/controllers/memberEditController.js"></script>
        <script src="~/app/controllers/requestsController.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LocationFormScriptsPartial.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        $('#CityId').change(function () {
            $('#DistrictId option').remove();
            $('#DistrictId').append('<option value>Chọn quận của bạn</option>');

            var cityId = $('#CityId').val();
            if (cityId) {
                $.get('/api/cities/' + cityId, function (data) {
                    $.each(data, function () {
                        $('#DistrictId').append('<option value=' +
                            this.id + '>' + this.name + '</option>');
                    });
                }).fail(function (err) {
                    swal(err.responseText, null, 'error');
                });
            }
        });
    });
</script>

Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TeamUp</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Teams" asp-action="Index">Tìm Đội</a></li>
                <li><a asp-area="" asp-controller="Members" asp-action="Index">Tuyển Thành Viên</a></li>
@*                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
            </ul>
            @await Component.InvokeAsync("LoginStatus")
        </div>
    </div>
</nav>

Views/Shared/_SideBar.cshtml
@inject UserManager<ApplicationUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}


<div class="sidebar info col-md-2">
    <div class="intrude-less">
        <header id="header" class="inner">
            <div class="avatar">
                <a href="/">
                    <div class="avatar__image">
                        <img src="~/images/avatars/noAvatar.png" alt="My Avatar"/>
                    </div>
                </a>
                <h1 class="avatar__title">@user.Name</h1>
                <p class="avatar__subtitle">@user.Team?.Name</p>
            </div>

            <nav id="main-nav">
                <ul class="main-navigation">
                    @if (user.TeamId.HasValue)
                    {
                        <li><a asp-controller="Teams" asp-action="Info" asp-route-id="@user.TeamId">Đội Bóng</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Teams" asp-action="Create" asp-route-id="@user.TeamId">Tạo Đội</a></li>
                    }
                    <li><a href="#">Yêu Cầu</a></li>
                    <li><a asp-controller="Members" asp-action="Edit">Cá nhân</a></li>
                    <li><a href="#">Tin Nhắn</a></li>
                    <li><a href="#">Thoát</a></li>
                </ul>
            </nav>
            <nav id="sub-nav">
            </nav>
        </header>
    </div>

</div>